### ISSUE TITLE
`pkg_tar` ignores Python toolchain

### ISSUE THREAD

**Issue by bmclarnon** [bazelbuild/rules_pkg#926]
`pkg_tar` delegates to [`build_tar.py`](https://github.com/bazelbuild/rules_pkg/blob/main/pkg/private/tar/build_tar.py) to construct the output tar file. When that tool is run, the system python3 interpreter is used, regardless of the default Bazel python toolchain.

In most cases, this isn't an issue because python3 is available in the path and `build_tar`'s output isn't affected by the Python version, but it's inconvenient when using [remote execution](https://bazel.build/remote/rbe): it requires that python3 is present in the build image -- even if the WORKSPACE registers a hermetic Python toolchain.

I verified the issue exists in 1.0.1 with a pretty old version of Bazel (6.5.0). I'm not sure if any rules_pkg rules besides `pkg_tar` are affected.

I believe the fix is straightforward: make the `pkg_tar` rule also depend on the current Python toolchain and include the corresponding runfiles in the `ctx.actions.run()` call. This should work with both platform and in-build runtimes based on the [`PyRuntimeInfo`](https://bazel.build/versions/7.0.0/rules/lib/providers/PyRuntimeInfo) documentation.

```diff
--- pkg/private/tar/tar.bzl
+++ pkg/private/tar/tar.bzl
@@ -187,16 +187,21 @@ def _pkg_tar_impl(ctx):
+    py3_runtime = ctx.toolchains["@bazel_tools//tools/python:toolchain_type"].py3_runtime
     ctx.actions.run(
         mnemonic = "PackageTar",
         progress_message = "Writing: %s" % output_file.path,
         inputs = inputs,
-        tools = [ctx.executable.compressor] if ctx.executable.compressor else [],
+        tools = (
+            [ctx.executable.compressor] if ctx.executable.compressor else [] +
+            [py3_runtime.files] if py3_runtime.files else []
+        ),
         executable = ctx.executable._build_tar,
         arguments = [args],
         outputs = [output_file],
         env = {
             "LANG": "en_US.UTF-8",
             "LC_CTYPE": "UTF-8",
             "PYTHONIOENCODING": "UTF-8",
             "PYTHONUTF8": "1",
+            "PATH": "$PATH" + (":" + py3_runtime.interpreter.dirname if py3_runtime.interpreter else ""),
         },
         use_default_shell_env = True,
     )
@@ -310,3 +315,4 @@ pkg_tar_impl = rule(
         ),
     },
+    toolchains = ["@bazel_tools//tools/python:toolchain_type"],
 )
```

I'm happy to send a PR if you agree this is worth fixing. I'm also relatively new to Starlark, so I'm also very open to suggestions. Thanks!

**Comment by aiuto** [comment]
I'm not going to be able to answer any questions until 1/27 because of a
family issue.

**Comment by bmclarnon** [comment]
Of course -- and thanks for the heads up!

**Comment by bmclarnon** [comment]
Hi @aiuto, I was wondering if you'd had a chance to think about this more. Thanks!

**Comment by bmclarnon** [comment]
Turns out that this was fixed at the rules_python level as part of  https://github.com/bazelbuild/rules_python/issues/691.  I was able to fix this issue by setting `--@rules_python//python/config_settings:bootstrap_impl=script`, which requires rules_python >= 0.33.0 and bazel >= 7.

**Comment by iursino** [comment]
My bazel version is 7.6.1 and my rule_python version is "1.7.0"

Config:

```
# Python because I don't want to install it on the system.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = "3.12")
python.toolchain(
    python_version = "3.12",
    is_default = True,
)
use_repo(python, "python_3_11")
```

My rules_pkg is configured this way: 

```
bazel_dep(name = "rules_pkg", version = "1.1.0")
```

And I still get the `env: 'python3': No such file or directory` issue.

**Comment by tonyaiuto** [comment]
Why don't you try the patch in the first comment on this issue and see if that resolves it for you.
TBH, for any python to work, I've had to resort to what @bmclarnon did.  In our project .bazelrc I have
```
common --@rules_python//python/config_settings:bootstrap_impl=script
```
Also, don't you mean `use_repo(python, "python_3_12")` rather than `python_3_11`?
